### ISSUE TITLE
Unbonded Surface Condition in MLE_bc.m

### ISSUE THREAD

**Issue by Mostafa-Nakhaei** [MartinScavone/ProductOneME#1]
Hi Martin
I wonder if your MLE program can handle friction-less interface between pavement layers? I tried to develop an MLE program using Huang book equations, everything works fine but not frictionless condition.
Thanks
Mostafa

**Comment by MartinScavone** [comment]
Hi, sorry for the late reply (I just happen to enter my github channel after a long while [uploading an untested improved version of this with (partial, unfinished) concrete pavement support] and saw your question by chance). 
I just went through the code, comparing equations with Huang's book. As the program is right now, it cannot handle friction-less interfaces. But, if you'd want to do so, you may want to start by modifying the LM and RM variables in the MLE_bc funciton [which is inside the '/elasticlinearanalysis' folder. (Currently, LM and RM) are the matrix in Huang's equation B.11. The friction-less case is equation B.17). If you wish to do so, you may also need to modify the MLE_sigma function to use the new frictionless case.
I haven't tried the equations myself, so I cannot attest anything about whether they're correct or not. But, if you want to do comparisons of results with other implementartions, here are some:
-> Check the Matlab Central for another MLE implementation by some Iraqi guy (I forgot his name, but it's the only one -besides mine- that is)
-> There's also ALVA, published by Danish authors (launched late last year): https://data.dtu.dk/articles/ALVA/12387305
-> And there's OpenPAVE (which is programmed into an Excel spreadsheet [must enable macros to run!]. Google search: OpenPave.org.
Also, Huang's book has an error in the equation for the vertical displacement (B.4e) - it's missing an H term (total thickness of pavement). It's written correctly in Caicedo's (2019) book ["Geotechnics of roads: Fundamentals", CRC], and in a recent thesis on visco-elastic analysis of deflections measured with the Raptor RWD: [Athanasiadis and Zoulis (2019)]

It may be a lot of stuff altogether, hope it's helpful.

Regards,
Martin S.

**Comment by Mostafa-Nakhaei** [comment]
Hey Martin
Thanks for your comment.
I read your dissertation and great job. The Huang equation is wrong in horizontal displacement as well and took me a while to figure out. I am aware of Matlab version of the MLE. All programs have problem in surface accuracy as well, https://github.com/asmusskar/ALVA is the first open-source implementation that consider newer methods to address surface imprecision.

**Comment by MartinScavone** [comment]
Thanks for the +1 feedback! Great to know that writing this pieces of code and releasing them publicly are inspiring further work. Feel free to use Prod-One's source code to build up any project of yours, my only condition is that the day you release your end-products, you bind them to the same CC license I've used for Prod-One...

Happy Sunday!
